FOSS: true

ITSERVICES:
  - ZOOKEEPER:
      image: confluent/zookeeper:3.4.6-cp1
      env:
          - zk_id: "1"
      sleep: 10

  - KAFKA:
      image: confluent/kafka:0.10.0.0-cp1
      env:
        - KAFKA_ZOOKEEPER_CONNECT=%%ZOOKEEPER:2181
        - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1

ITPARAMETERS: >
      -Dzookeeper.hosts=%%ZOOKEEPER:2181
      -Dkafka.hosts=%%KAFKA:9092
