# sudo -i
# curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# weave launch-router --dns-domain="qa.stratio.com." --init-peer-count 1 && weave launch-proxy -H tcp://0.0.0.0:12375
# weave expose
# eval $(weave env)

zookeeper:
      image: confluent/zookeeper:3.4.6-cp1
      container_name: zookeeper
      ports:
            - "2181:2181"
      environment:
        zk_id: "1"

kafka:
      image: confluent/kafka:0.10.0.0-cp1
      container_name: kafka
      links:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper.qa.stratio.com:2181
        KAFKA_ADVERTISED_HOST_NAME: kafka.qa.stratio.com

# docker-compose -f kafka-confluent-compose.yml up
# eval $(weave env --restore)